"""Adds assignments for topics 2-4 (only topic 1 had any before this).

This script only creates structure (assignments) -- no submissions. All submission/
mastery data across every student is generated by the final step in the chain,
scripts/seed_demo_dataset.py, so there's exactly one place that decides what a
student's grade history looks like instead of it being scattered across several scripts.

Run once: python -m scripts.seed_submissions
"""
from app.db import SessionLocal
from app.models import Assignment
from scripts._seed_common import ESSAY_RUBRIC

SEEDED_TOPIC_IDS = [2, 3, 4]

NEW_ASSIGNMENTS = [
    {"topic_id": 2, "type": "essay", "prompt": "Solve 2x + 3 = 11 and explain each step of your reasoning.", "rubric": ESSAY_RUBRIC},
    {"topic_id": 2, "type": "mcq", "prompt": "What is the value of x in 2x + 3 = 11?", "rubric": {"options": ["2", "4", "8"], "correct_answer": "4"}},
    {"topic_id": 3, "type": "essay", "prompt": "A train travels 90 miles in 2 hours. Show how you'd find its average speed.", "rubric": ESSAY_RUBRIC},
    {"topic_id": 3, "type": "mcq", "prompt": "A train travels 90 miles in 2 hours. What is its average speed in mph?", "rubric": {"options": ["35", "45", "55"], "correct_answer": "45"}},
    {"topic_id": 4, "type": "essay", "prompt": "Solve x^2 - 5x + 6 = 0 by factoring, and explain each step.", "rubric": ESSAY_RUBRIC},
    {"topic_id": 4, "type": "mcq", "prompt": "What are the roots of x^2 - 5x + 6 = 0?", "rubric": {"options": ["2 and 3", "1 and 6", "-2 and -3"], "correct_answer": "2 and 3"}},
]


def main() -> None:
    db = SessionLocal()

    if db.query(Assignment).filter(Assignment.topic_id.in_(SEEDED_TOPIC_IDS)).first():
        print("Assignments for topics 2-4 already exist — this script has already run, skipping.")
        return

    for spec in NEW_ASSIGNMENTS:
        db.add(Assignment(topic_id=spec["topic_id"], type=spec["type"], prompt=spec["prompt"], rubric=spec["rubric"]))
    db.commit()

    print(f"Added {len(NEW_ASSIGNMENTS)} assignments across topics 2-4.")


if __name__ == "__main__":
    main()