"""Sprint 6 hardening: bring the demo dataset up to the backlog's own targets.

Adds a 5th topic -- a real prerequisite convergence (needs both Word Problems and
Quadratic Equations), not just a longer chain -- its assignments, and 5 more students.

This script only creates structure (topic, assignments, accounts) -- no submissions.
All submission/mastery data across every student is generated by the final step in the
chain, scripts/seed_demo_dataset.py, so there's exactly one place that decides what a
student's grade history looks like instead of it being scattered across several scripts.

Run once: python -m scripts.seed_hardening
"""
from app.db import SessionLocal
from app.models import Assignment, Topic, User
from app.security import hash_password
from scripts._seed_common import ESSAY_RUBRIC

NEW_TOPIC_NAME = "Quadratic Word Problems"

NEW_TOPIC_ASSIGNMENTS = [
    {
        "type": "essay",
        "prompt": "A ball's height is modeled by h = -x^2 + 6x. After how many seconds does it hit the ground (h=0)? Show your work.",
        "rubric": ESSAY_RUBRIC,
    },
    {
        "type": "mcq",
        "prompt": "A ball's height is modeled by h = -x^2 + 6x. At what two x-values does it hit the ground (h=0)?",
        "rubric": {"options": ["x=0 and x=6", "x=1 and x=5", "x=2 and x=4"], "correct_answer": "x=0 and x=6"},
    },
]

NEW_STUDENTS = [
    {"name": "Zoe Bennett", "email": "zoe.bennett@test.com"},
    {"name": "Marcus Webb", "email": "marcus.webb@test.com"},
    {"name": "Priya Sharma", "email": "priya.sharma@test.com"},
    {"name": "Ethan Brooks", "email": "ethan.brooks@test.com"},
    {"name": "Grace Nguyen", "email": "grace.nguyen@test.com"},
]


def main() -> None:
    db = SessionLocal()

    if db.query(Topic).filter(Topic.name == NEW_TOPIC_NAME).first():
        print("Hardening data already seeded (new topic exists) -- skipping.")
        return

    new_topic = Topic(name=NEW_TOPIC_NAME, prerequisite_ids=[3, 4])
    db.add(new_topic)
    db.flush()  # need new_topic.id before attaching its assignments

    for spec in NEW_TOPIC_ASSIGNMENTS:
        db.add(Assignment(topic_id=new_topic.id, type=spec["type"], prompt=spec["prompt"], rubric=spec["rubric"]))

    for spec in NEW_STUDENTS:
        db.add(User(name=spec["name"], email=spec["email"], role="student", password_hash=hash_password("pass1234")))
    db.commit()

    print(f"Added topic '{NEW_TOPIC_NAME}' (id={new_topic.id}) with {len(NEW_TOPIC_ASSIGNMENTS)} assignments "
          f"and {len(NEW_STUDENTS)} new students.")


if __name__ == "__main__":
    main()