"""Bootstraps the base demo dataset from a genuinely empty database.

Run this FIRST, immediately after `alembic upgrade head` -- before the other seed
scripts, all of which assume this base data (staff accounts, the original 6 students,
the original 4 topics, and topic 1's assignments) already exists. Previously that base
dataset only existed in the live Docker volume, built up interactively across earlier
sessions, with nothing reproducing it from scratch. This closes that gap.

This script only creates structure (accounts, topics, assignments) -- no submissions.
All submission/mastery data across every student is generated by the final step in the
chain, scripts/seed_demo_dataset.py, so there's exactly one place that decides what a
student's grade history looks like instead of it being scattered across several scripts.

Run once: python -m scripts.seed_base
"""
from app.db import SessionLocal
from app.models import Assignment, Topic, User
from app.security import hash_password

STAFF = [
    {"name": "Test Teacher", "email": "teacher2@test.com", "role": "teacher"},
    {"name": "Test Admin", "email": "admin@test.com", "role": "admin"},
]

STUDENTS = [
    {"name": "Test Student", "email": "student@test.com"},
    {"name": "Ava Martinez", "email": "ava.martinez@test.com"},
    {"name": "Liam Chen", "email": "liam.chen@test.com"},
    {"name": "Noah Patel", "email": "noah.patel@test.com"},
    {"name": "Sophia Kim", "email": "sophia.kim@test.com"},
    {"name": "Mason Rivera", "email": "mason.rivera@test.com"},
]

# Prerequisites are resolved by name, not hardcoded id -- a bootstrap script is exactly
# the place a hardcoded-id assumption would be tempting (and exactly the mistake that
# broke seed_hardening.py's first run: it assumed a new topic would get id 5, but
# leftover state from unrelated testing had already advanced the sequence past that).
TOPICS = [
    {"name": "Intro to Algebra", "prerequisites": []},
    {"name": "Linear Equations", "prerequisites": ["Intro to Algebra"]},
    {"name": "Word Problems", "prerequisites": ["Linear Equations"]},
    {"name": "Quadratic Equations", "prerequisites": ["Linear Equations"]},
]

TOPIC_1_ASSIGNMENTS = [
    {
        "type": "essay",
        "prompt": "Write a 2 page essay explaining what you learned in the first week of class today!",
        "rubric": {"criteria": [
            {"criterion": "Intro", "weight": 0.2},
            {"criterion": "Body", "weight": 0.6},
            {"criterion": "Conclusion", "weight": 0.2},
        ]},
    },
    {
        "type": "mcq",
        "prompt": "What is the powerhouse of the cell?",
        "rubric": {"options": ["Nucleus", "Mitochondria", "Ribosome"], "correct_answer": "Mitochondria"},
    },
]


def main() -> None:
    db = SessionLocal()

    if db.query(Topic).first():
        print("Base dataset already exists (a topic is already present) -- skipping.")
        return

    for spec in STAFF:
        db.add(User(name=spec["name"], email=spec["email"], role=spec["role"], password_hash=hash_password("pass1234")))
    for spec in STUDENTS:
        db.add(User(name=spec["name"], email=spec["email"], role="student", password_hash=hash_password("pass1234")))
    db.commit()

    topics_by_name = {}
    for spec in TOPICS:
        prerequisite_ids = [topics_by_name[name].id for name in spec["prerequisites"]]
        topic = Topic(name=spec["name"], prerequisite_ids=prerequisite_ids)
        db.add(topic)
        db.flush()  # later topics reference this one's id as a prerequisite
        topics_by_name[spec["name"]] = topic
    db.commit()

    topic_1 = topics_by_name["Intro to Algebra"]
    for spec in TOPIC_1_ASSIGNMENTS:
        assignment = Assignment(topic_id=topic_1.id, type=spec["type"], prompt=spec["prompt"], rubric=spec["rubric"])
        db.add(assignment)
    db.commit()

    print(f"Seeded {len(STAFF)} staff accounts, {len(STUDENTS)} students, "
          f"{len(TOPICS)} topics, and {len(TOPIC_1_ASSIGNMENTS)} assignments for topic 1.")


if __name__ == "__main__":
    main()