"""add trend to mastery_scores

Revision ID: 2be20b52da21
Revises: 2b170d7198e6
Create Date: 2026-07-27 11:47:07.926672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be20b52da21'
down_revision: Union[str, Sequence[str], None] = '2b170d7198e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mastery_scores', sa.Column('trend', sa.String(), server_default='flat', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mastery_scores', 'trend')
    # ### end Alembic commands ###
