"""add unique constraint on mastery_scores

Revision ID: f8f06f1cd499
Revises: 5828a1b8be18
Create Date: 2026-07-24 15:48:30.335455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f06f1cd499'
down_revision: Union[str, Sequence[str], None] = '5828a1b8be18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mastery_scores', ['student_id', 'topic_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mastery_scores', type_='unique')
    # ### end Alembic commands ###
